version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"  # <--- This dash must be directly under the dash above
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
